### ISSUE TITLE
编辑按钮始终链向jaywcjlove/reference仓库且无法关闭编辑按钮

### ISSUE THREAD

**Issue by liesauer** [jaywcjlove/refs-cli#6]
假设我做了一份自己的reference，那么编辑按钮链向`jaywcjlove/reference`肯定是不对的，而且如果我的reference是对外面向其他人员的话，我是希望关闭编辑按钮功能的。希望能通过配置的方式修改编辑链向仓库和关闭编辑功能。

https://github.com/jaywcjlove/refs-cli/blob/f0a76dac9d8055380eb3f749003f884e5e1e4772/src/utils/utils.ts#L84-L86

https://github.com/jaywcjlove/refs-cli/blob/f0a76dac9d8055380eb3f749003f884e5e1e4772/src/nodes/header.ts#L80-L86

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/refs-cli/blob/baca3742a014c857603b66bd36f85d88319fc0c0/.refsrc.json#L14-L15

@liesauer 添加配置即可，更新到 `v1.2.15`

**Comment by liesauer** [comment]
你好，方便连同编辑按钮也可配置不显示嘛，我有一些非开源的文档并不想提供编辑功能。

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/refs-cli/blob/3820fe196c22af72c178117d5072d46d6344ee98/src/utils/utils.ts#L32-L35

@liesauer 更新到 `v1.3.0`

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/refs-cli/blob/3820fe196c22af72c178117d5072d46d6344ee98/.refsrc.json#L11-L13

```json
{
  "editor": {
    "disabled": true
  }
}
```

**Comment by liesauer** [comment]
感谢！
